version: '3.9'
services:
  app:
    build: .
    container_name: rph-search
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: rph-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
